{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE Safe #-}
-- | The Cryptol backend on Hyle: the width-preserving embedding of
--   doc/hyle.md, section 8.4. Every Hyle defn becomes a Cryptol function
--   over bitvectors; the device becomes a step function @rw_step@ (registers
--   and inputs to outputs and next-register values, as one concatenated
--   vector) wrapped in the standard Mealy stream idiom @rw_device@, matching
--   the Hyle interpreter bit for bit.
--
--   Because Hyle widths are explicit and exact, no width reconstruction
--   happens here: slices flip to Cryptol's MSB-first order, division gets
--   the SMT-LIB division-by-zero guard (doc/hyle.md, section 5.2), and
--   coercions and reductions map to small fixed helpers; everything else is
--   a per-construct template.
--
--   Combinational externs without models become uninterpreted functions in a
--   @parameter@ block (generic arguments become leading 32-bit arguments);
--   externs with models become ordinary calls to the model's function.
--   Devices with instances (sequential externs) are rejected: a pure target
--   has no equivalent.
module ReWire.Hyle.ToCryptol (compileProgram) where

import ReWire.Annotation (Annote, Annotated (ann))
import ReWire.BitVector (zeros, ones)

import qualified ReWire.BitVector as BV
import ReWire.Config (Config)
import ReWire.Cryptol.Syntax (cryptolName)
import ReWire.Error (failAt, failInternal, AstError, MonadError)
import ReWire.Hyle.Syntax
import ReWire.Pretty (showt)

import qualified ReWire.Cryptol.Syntax as Cry

import Control.Monad (foldM)
import Control.Monad.State (StateT, evalStateT, gets, modify)
import Data.HashMap.Strict (HashMap)
import Data.HashSet (HashSet)
import Data.List (sortOn)
import Data.Text (Text)

import qualified Data.HashMap.Strict as Map
import qualified Data.HashSet        as Set
import qualified Data.Text           as T

-- | Global environment: Hyle global names to Cryptol names; extern decls.
data Env = Env
      { envNames   :: HashMap GId Cry.Name
      , envExterns :: HashMap Name Extern
      , envExtNames :: HashMap Name Cry.Name -- ^ Extern to its parameter-block name.
      }

-- | Per-defn state: a fresh counter, the where-bindings in creation order,
--   and the local-name map (Hyle locals to legal Cryptol locals).
data TCS = TCS
      { tcsCtr    :: !Int
      , tcsBinds  :: ![Cry.Bind]
      , tcsLocals :: !(HashMap Name Cry.Name)
      }

type TCM m = StateT TCS m

compileProgram :: forall m. MonadError AstError m => Config -> Program -> m Cry.Module
compileProgram _conf (Program exts ds dev) = do
      case devInstances dev of
            Instance an _ ex _ : _ -> failAt an $ "clocked extern " <> ex
                                  <> " cannot be translated to a pure Cryptol function."
            []                    -> pure ()
      defns <- mapM (transDefn env) ds
      step  <- stepDefn env dev
      pure $ Cry.Module modName comments params $ defns <> [step, deviceDefn dev]
      where env :: Env
            env = Env names (Map.fromList $ map (\ e -> (extName e, e)) exts) extNames

            (names, extNames) = buildNames ds exts

            modName :: Cry.Name
            modName | T.null top = "device"
                    | otherwise  = top
                  where top = cryptolName $ devName dev

            comments :: [Text]
            comments = [ "Generated by rwc from device: " <> devName dev <> "."
                       , "rw_device maps a sequence of per-cycle inputs to per-cycle outputs."
                       ]

            -- | Model-less combinational externs, as uninterpreted functions:
            --   generic parameters become leading 32-bit arguments.
            params :: [Cry.Param]
            params = sortOn (\ (Cry.Param n _ _) -> n)
                  [ Cry.Param n (map (const 32) (extGenerics e) <> map snd (extInputs e)) (externResultSize e)
                  | e <- exts
                  , extModel e == Nothing
                  , extKind e == Comb
                  , Just n <- [Map.lookup (extName e) extNames]
                  ]

-- | Assigns each defn a Cryptol name @rw_<sanitized>@ and each extern
--   @ext_<sanitized>@, deduplicating with numeric suffixes and avoiding the
--   reserved @rw_step@/@rw_device@.
buildNames :: [Defn] -> [Extern] -> (HashMap GId Cry.Name, HashMap Name Cry.Name)
buildNames ds exts = (dnames, extnames)
      where (dnames, used') = foldl' (add "rw_") (mempty, Set.fromList ["rw_device", "rw_step"]) $ map defnName ds
            (extnames, _)   = foldl' (add "ext_") (mempty, used') $ map extName exts

            add :: Text -> (HashMap Text Cry.Name, HashSet Cry.Name) -> Text -> (HashMap Text Cry.Name, HashSet Cry.Name)
            add pfx (m, used) k = (Map.insert k n m, Set.insert n used)
                  where n = freshen used $ pfx <> cryptolName k

            freshen :: HashSet Cry.Name -> Cry.Name -> Cry.Name
            freshen used b | b `Set.member` used = go (2 :: Int)
                           | otherwise           = b
                  where go i | n `Set.member` used = go $ i + 1
                             | otherwise           = n
                              where n = b <> "_" <> showt i

-- | Look up a defn's Cryptol name.
defnNm' :: MonadError AstError m => Env -> Annote -> GId -> m Cry.Name
defnNm' env an g = case Map.lookup g $ envNames env of
      Just n  -> pure n
      Nothing -> failInternal an $ "unknown definition: " <> g

fresh :: Monad m => TCM m Cry.Name
fresh = do
      ctr <- gets tcsCtr
      modify $ \ ts -> ts { tcsCtr = ctr + 1 }
      pure $ "s" <> showt ctr

-- | Bind a Hyle local name to a fresh Cryptol local.
bindLocal :: Monad m => Name -> TCM m Cry.Name
bindLocal x = do
      n <- fresh
      modify $ \ ts -> ts { tcsLocals = Map.insert x n $ tcsLocals ts }
      pure n

pushBind :: Monad m => Cry.Name -> Size -> Cry.Exp -> TCM m ()
pushBind n sz e = modify $ \ ts -> ts { tcsBinds = tcsBinds ts <> [Cry.Bind n (Cry.TBits sz) e] }

transDefn :: MonadError AstError m => Env -> Defn -> m Cry.Defn
transDefn env (Defn an g (Sig _ argSzs res) ps body) = flip evalStateT (TCS 0 [] mempty) $ do
      let xs = zipWith (\ i _ -> "x" <> showt i) [0 :: Int ..] ps
      modify $ \ ts -> ts { tcsLocals = Map.fromList $ zip ps xs }
      n     <- defnNm' env an g
      e     <- transExp env body
      binds <- gets tcsBinds
      pure $ Cry.Defn comments n False (zip xs $ map Cry.TBits argSzs) (Cry.TBits res) e binds
      where comments :: [Text]
            comments = [g | cryptolName g /= g]

transExp :: forall m. MonadError AstError m => Env -> Exp -> TCM m Cry.Exp
transExp env = go
      where go :: Exp -> TCM m Cry.Exp
            go = \ case
                  Lit _ bv        -> pure $ Cry.Lit bv
                  Undef _ sz      -> pure $ Cry.Lit $ zeros $ fromIntegral sz
                  Var an _ x      -> gets (Map.lookup x . tcsLocals) >>= \ case
                        Just n  -> pure $ Cry.Var n
                        Nothing -> failInternal an $ "unbound variable: " <> x
                  e@Cat {}        -> Cry.cat <$> mapM go (gather e)
                  Slice _ i k e   -> Cry.slice (sizeOf e) (sizeOf e - fromIntegral i - k) k <$> go e
                  Prim an sz op es -> transPrim env an sz op es
                  Call an _ g es  -> Cry.Call <$> defnNm' env an g <*> mapM go es
                  XCall an _ x cs es -> case Map.lookup x $ envExterns env of
                        Nothing -> failAt an $ "unknown extern: " <> x
                        Just ex -> case extModel ex of
                              Just g  -> Cry.Call <$> defnNm' env an g <*> mapM go es
                              Nothing -> case Map.lookup x $ envExtNames env of
                                    Nothing -> failAt an $ "unknown extern: " <> x
                                    Just n  -> Cry.Call n . (map (Cry.Lit . BV.bitVec 32 . toInteger) cs <>) <$> mapM go es
                  If _ _ c t e    -> Cry.If <$> transBit env c <*> go t <*> go e
                  Let _ _ x e1 e2 -> do
                        e1' <- go e1
                        n   <- bindLocal x
                        pushBind n (sizeOf e1) e1'
                        go e2

-- | A [1]-valued Hyle expression as a Cryptol Bit: comparisons and
--   width-1 logical structure translate directly, anything else is indexed.
transBit :: forall m. MonadError AstError m => Env -> Exp -> TCM m Cry.Exp
transBit env e = case e of
      Prim _ _ op [a, b] | Just cop <- cmpName (sizeOf a) op
                        -> Cry.BinOp cop <$> transExp env a <*> transExp env b
      Prim _ 1 And [a, b] -> Cry.BinOp "&&" <$> transBit env a <*> transBit env b
      Prim _ 1 Or  [a, b] -> Cry.BinOp "||" <$> transBit env a <*> transBit env b
      Prim _ 1 Not [a]    -> Cry.UnOp "~" <$> transBit env a
      Prim _ 1 RedOr [a]  -> (\ a' -> Cry.BinOp "!=" a' (Cry.Var "zero")) <$> transExp env a
      _                   -> flip Cry.Index 0 <$> transExp env e
      where cmpName :: Size -> Op -> Maybe Cry.Name
            cmpName w = \ case
                  Eq  -> Just "=="
                  Ne  -> Just "!="
                  ULt -> Just "<"
                  ULe -> Just "<="
                  UGt -> Just ">"
                  UGe -> Just ">="
                  SLt | w >= 1 -> Just "<$"
                  SLe | w >= 1 -> Just "<=$"
                  SGt | w >= 1 -> Just ">$"
                  SGe | w >= 1 -> Just ">=$"
                  _   -> Nothing

-- | Primitive templates (doc/hyle.md, sections 5.2 and 8.2). Widths are
--   exact by construction, so no resizing happens except where the operator
--   itself changes width.
transPrim :: forall m. MonadError AstError m => Env -> Annote -> Size -> Op -> [Exp] -> TCM m Cry.Exp
transPrim env an sz op args = case (op, args) of
      (Add   , [a, b]) -> bin "+" a b
      (Sub   , [a, b]) -> bin "-" a b
      (Mul   , [a, b]) -> bin "*" a b
      (Pow   , [a, b]) -> bin "^^" a b
      (UDiv  , [a, b]) -> divGuard b (allOnes $ sizeOf a) $ bin "/" a b
      (UMod  , [a, b]) -> divGuard b (transExp env a) $ bin "%" a b
      (And   , [a, b]) -> bin "&&" a b
      (Or    , [a, b]) -> bin "||" a b
      (XOr   , [a, b]) -> bin "^" a b
      (Not   , [a])    -> Cry.UnOp "~" <$> transExp env a
      (Shl   , [a, b]) -> bin "<<" a b
      (LShr  , [a, b]) -> bin ">>" a b
      (AShr  , [a, b])
            | sizeOf a == 0 -> pure Cry.nil
            | otherwise     -> bin ">>$" a b
      (Eq    , _)      -> cmp
      (Ne    , _)      -> cmp
      (ULt   , _)      -> cmp
      (ULe   , _)      -> cmp
      (UGt   , _)      -> cmp
      (UGe   , _)      -> cmp
      (SLt   , [a, _]) | sizeOf a == 0 -> pure false1
      (SGt   , [a, _]) | sizeOf a == 0 -> pure false1
      (SLe   , [a, _]) | sizeOf a == 0 -> pure true1
      (SGe   , [a, _]) | sizeOf a == 0 -> pure true1
      (SLt   , _)      -> cmp
      (SLe   , _)      -> cmp
      (SGt   , _)      -> cmp
      (SGe   , _)      -> cmp
      (RedAnd, [a])    -> (\ a' -> Cry.Sing $ Cry.BinOp "==" a' $ Cry.UnOp "~" $ Cry.Var "zero") <$> transExp env a
      (RedOr , [a])    -> (\ a' -> Cry.Sing $ Cry.BinOp "!=" a' $ Cry.Var "zero") <$> transExp env a
      (RedXOr, [a])    -> (\ a' -> Cry.Sing $ Cry.Call "rw'parity" [a']) <$> transExp env a
      (ZExt m, [a])    -> Cry.resize m <$> transExp env a
      (Trunc m, [a])   -> Cry.resize m <$> transExp env a
      (SExt m, [a])    -> (\ a' -> Cry.TCall "rw'sext" (fromIntegral m) [a']) <$> transExp env a
      (Rep k , [a])    -> (\ a' -> Cry.TCall "rw'repl" k [a']) <$> transExp env a
      _                -> failInternal an $ "ill-formed primitive application: " <> opName op <> " with " <> showt (length args) <> " arguments."
      where bin :: Cry.Name -> Exp -> Exp -> TCM m Cry.Exp
            bin o a b = Cry.BinOp o <$> transExp env a <*> transExp env b

            -- | Comparisons yield a Bit; wrap as [1].
            cmp :: TCM m Cry.Exp
            cmp = Cry.Sing <$> transBit env (Prim an sz op args)

            -- | SMT-LIB division by zero: a zero divisor yields the default.
            divGuard :: Exp -> TCM m Cry.Exp -> TCM m Cry.Exp -> TCM m Cry.Exp
            divGuard b dflt whole = do
                  b'  <- transExp env b
                  Cry.If (Cry.BinOp "==" b' $ Cry.Var "zero") <$> dflt <*> whole

            allOnes :: Size -> TCM m Cry.Exp
            allOnes w = pure $ Cry.Lit $ ones $ fromIntegral w

            false1, true1 :: Cry.Exp
            false1 = Cry.Lit $ zeros 1
            true1  = Cry.Lit $ ones 1

-- | The device's per-cycle step function: registers and inputs (each as one
--   concatenated vector, MSB-first in declaration order) to the
--   concatenation of outputs and next-register values.
stepDefn :: forall m. MonadError AstError m => Env -> Device -> m Cry.Defn
stepDefn env dev = flip evalStateT (TCS 0 [] mempty) $ do
      mapM_ bindSlice $ wireLayout "st" regWires
      mapM_ bindSlice $ wireLayout "i" $ devInputs dev
      (outs, nexts) <- foldM stmt (mempty, mempty) $ devBody dev
      result <- catOf outs (devOutputs dev) "output"
      result' <- catOf nexts regWires "register"
      binds <- gets tcsBinds
      pure $ Cry.Defn ["Per-cycle step: outputs # next register values."] "rw_step" False args (Cry.TBits $ ow + rsz)
            (Cry.cat $ result <> result') binds
      where regWires :: [(Name, Size)]
            regWires = [ (x, sz) | Register _ x sz _ <- devRegisters dev ]

            rsz, iw, ow :: Size
            rsz = sum $ map snd regWires
            iw  = sum $ map snd $ devInputs dev
            ow  = sum $ map snd $ devOutputs dev

            args :: [(Cry.Name, Cry.Ty)]
            args = [ ("st", Cry.TBits rsz) | rsz > 0 ] <> [ ("i", Cry.TBits iw) | iw > 0 ]

            -- | (wire name, width, MSB offset within the vector, vector name)
            wireLayout :: Cry.Name -> [(Name, Size)] -> [(Name, Size, Size, Cry.Name)]
            wireLayout v ws = snd $ foldl' (\ (off, acc) (x, sz) -> (off + sz, acc <> [(x, sz, off, v)])) (0, []) ws

            bindSlice :: (Name, Size, Size, Cry.Name) -> TCM m ()
            bindSlice (x, sz, off, v) = do
                  n <- bindLocal x
                  let total = if v == "st" then rsz else iw
                  pushBind n sz $ Cry.slice total off sz $ Cry.Var v

            stmt :: (HashMap Name Cry.Exp, HashMap Name Cry.Exp) -> Stmt -> TCM m (HashMap Name Cry.Exp, HashMap Name Cry.Exp)
            stmt (outs, nexts) = \ case
                  SLet _ x e -> do
                        e' <- transExp env e
                        n  <- bindLocal x
                        pushBind n (sizeOf e) e'
                        pure (outs, nexts)
                  SOutput _ x e -> (\ e' -> (Map.insert x e' outs, nexts)) <$> transExp env e
                  SNext _ x e   -> (\ e' -> (outs, Map.insert x e' nexts)) <$> transExp env e
                  SInstIn an' _ _ _ -> failInternal an' "instance input in a device without instances"

            catOf :: HashMap Name Cry.Exp -> [(Name, Size)] -> Text -> TCM m [Cry.Exp]
            catOf m ws what = mapM lk ws
                  where lk (x, _) = case Map.lookup x m of
                              Just e  -> pure e
                              Nothing -> failInternal (ann dev) $ what <> " " <> x <> " is never assigned"

-- | The Mealy-machine wrapper around @rw_step@ (the standard stream idiom):
--   @rw_step@'s result has the layout outputs # next-registers.
deviceDefn :: Device -> Cry.Defn
deviceDefn dev
      | rsz > 0 = Cry.Defn comments "rw_device" True [("ins", insTy)] outsTy (Cry.Var "outs")
            [ Cry.Bind "rs" (Cry.TSeq Cry.LenVar $ Cry.TBits $ ow + rsz)
                  $ Cry.Comp (Cry.Call "rw_step" $ [Cry.Var "st"] <> [Cry.Var "i" | iw > 0])
                  $ ("st", Cry.Var "sts") : [inArm]
            , Cry.Bind "sts" (Cry.TSeq Cry.LenSucc $ Cry.TBits rsz)
                  $ Cry.BinOp "#" (Cry.SeqLit [Cry.Lit inits])
                  $ Cry.Comp (nxt $ Cry.Var "r") [("r", Cry.Var "rs")]
            , Cry.Bind "outs" outsTy
                  $ Cry.Comp (out $ Cry.Var "r") [("r", Cry.Var "rs")]
            ]
      | otherwise = Cry.Defn comments "rw_device" True [("ins", insTy)] outsTy
            (Cry.Comp (out $ Cry.Call "rw_step" [Cry.Var "i" | iw > 0]) [inArm]) []
      where rsz, iw, ow :: Size
            rsz = sum [ sz | Register _ _ sz _ <- devRegisters dev ]
            iw  = sum $ map snd $ devInputs dev
            ow  = sum $ map snd $ devOutputs dev

            inits :: BV.BV
            inits = mconcat [ bv | Register _ _ _ bv <- devRegisters dev ]

            insTy, outsTy :: Cry.Ty
            insTy  = Cry.TSeq Cry.LenVar $ Cry.TBits iw
            outsTy = Cry.TSeq Cry.LenVar $ Cry.TBits ow

            inArm :: (Cry.Name, Cry.Exp)
            inArm | iw > 0    = ("i", Cry.Var "ins")
                  | otherwise = ("_", Cry.Var "ins")

            out, nxt :: Cry.Exp -> Cry.Exp
            out = Cry.slice (ow + rsz) 0 ow
            nxt = Cry.slice (ow + rsz) ow rsz

            comments :: [Text]
            comments = [ "Device: " <> devName dev
                       , "Inputs, MSB-first: "  <> wires (devInputs dev)
                       , "Outputs, MSB-first: " <> wires (devOutputs dev)
                       ]

            wires :: [(Name, Size)] -> Text
            wires = \ case
                  [] -> "(none)"
                  ws -> T.intercalate ", " $ map (\ (n, s) -> n <> " : [" <> showt s <> "]") ws
