name: rewire
version: 2.2.0
synopsis: A Haskell-to-Verilog/VHDL compiler
description: An experimental compiler for a subset of Haskell to Verilog and VHDL.
homepage: https://github.com/mu-chaco/ReWire
license: NONE
license-file: LICENSE
author:
  - Adam Procter
  - Chris Hathhorn <hathhorn@gmail.com>
  - Ian Graves
  - William L. Harrison
maintainer: Chris Hathhorn <hathhorn@gmail.com>
category: Language
build-type: Simple
github: mu-chaco/ReWire.git

ghc-options:
  - -Wall
  - -fno-warn-name-shadowing
  - -funbox-strict-fields
  - -O2
  - -optc-O3
  - -j8 +RTS -A64m -RTS
default-extensions:
  - LambdaCase
  - TupleSections
  - ViewPatterns

extra-source-files:
  - README.md
data-files:
  - tests/integration/*.hs
  - tests/integration/OD19/*.hs
  - tests/regression/Mods/*.hs
  - tests/regression/Mods/C/*.hs
  - tests/regression/*.hs
  - src/user/*.hs
  - src/user/ReWire/*.hs
  - src/user/RWC/*.hs

dependencies:
  - base ^>= 4.15
  - ghc ^>= 9.0
  - bytestring ^>= 0.10
  - containers ^>= 0.6
  - unordered-containers ^>= 0.2
  - deepseq ^>= 1.4.4
  - directory ^>= 1.3
  - exceptions ^>= 0.10
  - filepath ^>= 1.4
  - hashable ^>= 1.3
  - haskell-src-exts ^>= 1.23
  - mtl ^>= 2.2.1
  - prettyprinter ^>= 1.7
  - split ^>= 0.2
  - text ^>= 1.2
  - transformers ^>= 0.5
  - text-show ^>= 3.9
  - unbound-generics ^>= 0.4.1
  - monad-resumption ^>= 0.1.4.0
  - parsec ^>= 3.1.14
  - bv ^>= 0.5
  - machines ^>= 0.7.2
  - yaml ^>= 0.11.7

library:
  source-dirs: src/user

internal-libraries:
      rwc-lib:
            source-dirs: src/rwc
            dependencies:
                  - rewire-core
      rewire-core:
            source-dirs: src/rewire

executables:

  rwc:
    source-dirs: apps/rwc
    main: Main.hs
    dependencies:
      - rwc-lib

  rwcx:
    source-dirs: apps/rwcx
    main: Main.hs
    dependencies:
      - rewire-core
      - ghc-paths ^>= 0.1.0.12

  firrtl:
    source-dirs: apps/firrtl
    main: Main.hs
    dependencies:
      - rewire-core

tests:

  rwc-test:
    source-dirs: apps/rwc-test
    main: Main.hs
    dependencies:
      - rwc-lib
      - HUnit ^>= 1.6
      - directory ^>= 1.3
      - process ^>= 1.6
      - filepath ^>= 1.4
      - test-framework ^>= 0.8
      - test-framework-hunit ^>= 0.3.0.2
