name:         rewire
version:      2.5.0
synopsis:     A Haskell-to-Verilog/VHDL compiler
description:  An experimental compiler for a subset of Haskell to Verilog and VHDL.
homepage:     https://github.com/mu-chaco/ReWire
license:      NONE
license-file: LICENSE
category:     Language
build-type:   Simple
github:       twosixlabs/ReWire.git
maintainer:   Chris Hathhorn <hathhorn@gmail.com>
author:
- Adam Procter
- Chris Hathhorn <hathhorn@gmail.com>
- Ian Graves
- William L. Harrison

ghc-options:
- -Wall
- -fno-warn-name-shadowing
- -funbox-strict-fields
- -O2
- -optc-O3
- -j8 +RTS -A64m -RTS
default-extensions:
- LambdaCase
- TupleSections
- ViewPatterns

extra-source-files:
- README.md
data-files:
- tests/integration/*.hs
- tests/integration/OD19/*.hs
- tests/regression/Mods/*.hs
- tests/regression/Mods/C/*.hs
- tests/regression/*.hs
- rewire-user/src/*.hs
- rewire-user/src/RWC/*.hs
- rewire-user/src/ReWire/*.hs

dependencies:
- base ^>= 4.16
- ghc ^>= 9.2
- directory ^>= 1.3
- filepath ^>= 1.4
- lens ^>= 5.1
- rewire-user ^>= 0.1
- text ^>= 1.2

library:
  source-dirs: src
  dependencies:
  - rewire-core

executables:
  rwc:
    source-dirs: apps/rwc
    main: Main.hs
    dependencies:
    - rewire

  rwcx:
    source-dirs: apps/rwcx
    main: Main.hs
    dependencies:
    - rewire-core
    - ghc-paths ^>= 0.1.0.12

  firrtl:
    source-dirs: apps/firrtl
    main: Main.hs
    dependencies:
    - rewire-core

tests:
  rwc-test:
    source-dirs: apps/rwc-test
    main: Main.hs
    dependencies:
    - rewire
    - HUnit ^>= 1.6
    - directory ^>= 1.3
    - process ^>= 1.6
    - filepath ^>= 1.4
    - test-framework ^>= 0.8
    - test-framework-hunit ^>= 0.3.0.2
