data Main.Maybe4 =
    Main.Maybe4 Prelude.Maybe ReWirePrelude.W8 Prelude.Maybe ReWirePrelude.W8 Prelude.Maybe ReWirePrelude.W8 Prelude.Maybe ReWirePrelude.W8
data Main.Inp =
    Main.Inp Main.Maybe4 (,,,,,,,,,,,,,,,) Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool| Main.NoInput
data Main.Out =
    Main.Out Main.Maybe4| Main.Nix
data Prelude.Bool =
    Prelude.False| Prelude.True
data Prelude.Maybe a =
    Prelude.Nothing| Prelude.Just a
data Prelude.Either a b =
    Prelude.Left a| Prelude.Right b
data ReWirePrelude.Bit =
    ReWirePrelude.Zero| ReWirePrelude.One
data ReWirePrelude.W8 =
    ReWirePrelude.W8 ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit
data ReWirePrelude.W32 =
    ReWirePrelude.W32 ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit ReWirePrelude.Bit
Main.crossbar :: Main.Maybe4 -> (,,,,,,,,,,,,,,,) Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool Prelude.Bool -> Main.Maybe4
Main.crossbar =
    (\ $3 -> (\ $4 -> (case (((,) $3) $4) of
                           {(((,) (Main.Maybe4 x10 x20 x30 x40) ((,,,,,,,,,,,,,,,) c11 c12 c13 c14 c21 c22 c23 c24 c31 c32 c33 c34 c41 c42 c43 c44))) -> (case (case ((((,,)
                                                                                                                                                                            x40)
                                                                                                                                                                           Prelude.Nothing)
                                                                                                                                                                          c41) of
                                                                                                                                                                    {(((,,) x y (Prelude.True))) -> (((,) x)
                                                                                                                                                                                                         x) ; 
                                                                                                                                                                     _ -> (case ((((,,)
                                                                                                                                                                                       x40)
                                                                                                                                                                                      Prelude.Nothing)
                                                                                                                                                                                     c41) of
                                                                                                                                                                               {(((,,) x y (Prelude.False))) -> (((,) x)
                                                                                                                                                                                                                     y) ; 
                                                                                                                                                                                _ -> (primError "pattern match failure")})}) of
                                                                                                                                                              {(((,) x41 y31)) -> (case (case ((((,,)
                                                                                                                                                                                                     x30)
                                                                                                                                                                                                    y31)
                                                                                                                                                                                                   c31) of
                                                                                                                                                                                             {(((,,) x y (Prelude.True))) -> (((,) x)
                                                                                                                                                                                                                                  x) ; 
                                                                                                                                                                                              _ -> (case ((((,,)
                                                                                                                                                                                                                x30)
                                                                                                                                                                                                               y31)
                                                                                                                                                                                                              c31) of
                                                                                                                                                                                                        {(((,,) x y (Prelude.False))) -> (((,) x)
                                                                                                                                                                                                                                              y) ; 
                                                                                                                                                                                                         _ -> (primError "pattern match failure")})}) of
                                                                                                                                                                                       {(((,) x31 y21)) -> (case (case ((((,,)
                                                                                                                                                                                                                              x20)
                                                                                                                                                                                                                             y21)
                                                                                                                                                                                                                            c21) of
                                                                                                                                                                                                                      {(((,,) x y (Prelude.True))) -> (((,) x)
                                                                                                                                                                                                                                                           x) ; 
                                                                                                                                                                                                                       _ -> (case ((((,,)
                                                                                                                                                                                                                                         x20)
                                                                                                                                                                                                                                        y21)
                                                                                                                                                                                                                                       c21) of
                                                                                                                                                                                                                                 {(((,,) x y (Prelude.False))) -> (((,) x)
                                                                                                                                                                                                                                                                       y) ; 
                                                                                                                                                                                                                                  _ -> (primError "pattern match failure")})}) of
                                                                                                                                                                                                                {(((,) x21 y11)) -> (case (case ((((,,)
                                                                                                                                                                                                                                                       x41)
                                                                                                                                                                                                                                                      Prelude.Nothing)
                                                                                                                                                                                                                                                     c42) of
                                                                                                                                                                                                                                               {(((,,) x y (Prelude.True))) -> (((,) x)
                                                                                                                                                                                                                                                                                    x) ; 
                                                                                                                                                                                                                                                _ -> (case ((((,,)
                                                                                                                                                                                                                                                                  x41)
                                                                                                                                                                                                                                                                 Prelude.Nothing)
                                                                                                                                                                                                                                                                c42) of
                                                                                                                                                                                                                                                          {(((,,) x y (Prelude.False))) -> (((,) x)
                                                                                                                                                                                                                                                                                                y) ; 
                                                                                                                                                                                                                                                           _ -> (primError "pattern match failure")})}) of
                                                                                                                                                                                                                                         {(((,) x42 y32)) -> (case (case ((((,,)
                                                                                                                                                                                                                                                                                x31)
                                                                                                                                                                                                                                                                               y32)
                                                                                                                                                                                                                                                                              c32) of
                                                                                                                                                                                                                                                                        {(((,,) x y (Prelude.True))) -> (((,) x)
                                                                                                                                                                                                                                                                                                             x) ; 
                                                                                                                                                                                                                                                                         _ -> (case ((((,,)
                                                                                                                                                                                                                                                                                           x31)
                                                                                                                                                                                                                                                                                          y32)
                                                                                                                                                                                                                                                                                         c32) of
                                                                                                                                                                                                                                                                                   {(((,,) x y (Prelude.False))) -> (((,) x)
                                                                                                                                                                                                                                                                                                                         y) ; 
                                                                                                                                                                                                                                                                                    _ -> (primError "pattern match failure")})}) of
                                                                                                                                                                                                                                                                  {(((,) x32 y22)) -> (case (case ((((,,)
                                                                                                                                                                                                                                                                                                         x21)
                                                                                                                                                                                                                                                                                                        y22)
                                                                                                                                                                                                                                                                                                       c22) of
                                                                                                                                                                                                                                                                                                 {(((,,) x y (Prelude.True))) -> (((,) x)
                                                                                                                                                                                                                                                                                                                                      x) ; 
                                                                                                                                                                                                                                                                                                  _ -> (case ((((,,)
                                                                                                                                                                                                                                                                                                                    x21)
                                                                                                                                                                                                                                                                                                                   y22)
                                                                                                                                                                                                                                                                                                                  c22) of
                                                                                                                                                                                                                                                                                                            {(((,,) x y (Prelude.False))) -> (((,) x)
                                                                                                                                                                                                                                                                                                                                                  y) ; 
                                                                                                                                                                                                                                                                                                             _ -> (primError "pattern match failure")})}) of
                                                                                                                                                                                                                                                                                           {(((,) x22 y12)) -> (case (case ((((,,)
                                                                                                                                                                                                                                                                                                                                  x10)
                                                                                                                                                                                                                                                                                                                                 y11)
                                                                                                                                                                                                                                                                                                                                c11) of
                                                                                                                                                                                                                                                                                                                          {(((,,) x y (Prelude.True))) -> (((,) x)
                                                                                                                                                                                                                                                                                                                                                               x) ; 
                                                                                                                                                                                                                                                                                                                           _ -> (case ((((,,)
                                                                                                                                                                                                                                                                                                                                             x10)
                                                                                                                                                                                                                                                                                                                                            y11)
                                                                                                                                                                                                                                                                                                                                           c11) of
                                                                                                                                                                                                                                                                                                                                     {(((,,) x y (Prelude.False))) -> (((,) x)
                                                                                                                                                                                                                                                                                                                                                                           y) ; 
                                                                                                                                                                                                                                                                                                                                      _ -> (primError "pattern match failure")})}) of
                                                                                                                                                                                                                                                                                                                    {(((,) x11 y10)) -> (case (case ((((,,)
                                                                                                                                                                                                                                                                                                                                                           x11)
                                                                                                                                                                                                                                                                                                                                                          y12)
                                                                                                                                                                                                                                                                                                                                                         c12) of
                                                                                                                                                                                                                                                                                                                                                   {(((,,) x y (Prelude.True))) -> (((,) x)
                                                                                                                                                                                                                                                                                                                                                                                        x) ; 
                                                                                                                                                                                                                                                                                                                                                    _ -> (case ((((,,)
                                                                                                                                                                                                                                                                                                                                                                      x11)
                                                                                                                                                                                                                                                                                                                                                                     y12)
                                                                                                                                                                                                                                                                                                                                                                    c12) of
                                                                                                                                                                                                                                                                                                                                                              {(((,,) x y (Prelude.False))) -> (((,) x)
                                                                                                                                                                                                                                                                                                                                                                                                    y) ; 
                                                                                                                                                                                                                                                                                                                                                               _ -> (primError "pattern match failure")})}) of
                                                                                                                                                                                                                                                                                                                                             {(((,) x12 y20)) -> (case (case ((((,,)
                                                                                                                                                                                                                                                                                                                                                                                    x42)
                                                                                                                                                                                                                                                                                                                                                                                   Prelude.Nothing)
                                                                                                                                                                                                                                                                                                                                                                                  c43) of
                                                                                                                                                                                                                                                                                                                                                                            {(((,,) x y (Prelude.True))) -> (((,) x)
                                                                                                                                                                                                                                                                                                                                                                                                                 x) ; 
                                                                                                                                                                                                                                                                                                                                                                             _ -> (case ((((,,)
                                                                                                                                                                                                                                                                                                                                                                                               x42)
                                                                                                                                                                                                                                                                                                                                                                                              Prelude.Nothing)
                                                                                                                                                                                                                                                                                                                                                                                             c43) of
                                                                                                                                                                                                                                                                                                                                                                                       {(((,,) x y (Prelude.False))) -> (((,) x)
                                                                                                                                                                                                                                                                                                                                                                                                                             y) ; 
                                                                                                                                                                                                                                                                                                                                                                                        _ -> (primError "pattern match failure")})}) of
                                                                                                                                                                                                                                                                                                                                                                      {(((,) x43 y33)) -> (case (case ((((,,)
                                                                                                                                                                                                                                                                                                                                                                                                             x32)
                                                                                                                                                                                                                                                                                                                                                                                                            y33)
                                                                                                                                                                                                                                                                                                                                                                                                           c33) of
                                                                                                                                                                                                                                                                                                                                                                                                     {(((,,) x y (Prelude.True))) -> (((,) x)
                                                                                                                                                                                                                                                                                                                                                                                                                                          x) ; 
                                                                                                                                                                                                                                                                                                                                                                                                      _ -> (case ((((,,)
                                                                                                                                                                                                                                                                                                                                                                                                                        x32)
                                                                                                                                                                                                                                                                                                                                                                                                                       y33)
                                                                                                                                                                                                                                                                                                                                                                                                                      c33) of
                                                                                                                                                                                                                                                                                                                                                                                                                {(((,,) x y (Prelude.False))) -> (((,) x)
                                                                                                                                                                                                                                                                                                                                                                                                                                                      y) ; 
                                                                                                                                                                                                                                                                                                                                                                                                                 _ -> (primError "pattern match failure")})}) of
                                                                                                                                                                                                                                                                                                                                                                                               {(((,) x33 y23)) -> (case (case ((((,,)
                                                                                                                                                                                                                                                                                                                                                                                                                                      x22)
                                                                                                                                                                                                                                                                                                                                                                                                                                     y23)
                                                                                                                                                                                                                                                                                                                                                                                                                                    c23) of
                                                                                                                                                                                                                                                                                                                                                                                                                              {(((,,) x y (Prelude.True))) -> (((,) x)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   x) ; 
                                                                                                                                                                                                                                                                                                                                                                                                                               _ -> (case ((((,,)
                                                                                                                                                                                                                                                                                                                                                                                                                                                 x22)
                                                                                                                                                                                                                                                                                                                                                                                                                                                y23)
                                                                                                                                                                                                                                                                                                                                                                                                                                               c23) of
                                                                                                                                                                                                                                                                                                                                                                                                                                         {(((,,) x y (Prelude.False))) -> (((,) x)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               y) ; 
                                                                                                                                                                                                                                                                                                                                                                                                                                          _ -> (primError "pattern match failure")})}) of
                                                                                                                                                                                                                                                                                                                                                                                                                        {(((,) x23 y13)) -> (case (case ((((,,)
                                                                                                                                                                                                                                                                                                                                                                                                                                                               x12)
                                                                                                                                                                                                                                                                                                                                                                                                                                                              y13)
                                                                                                                                                                                                                                                                                                                                                                                                                                                             c13) of
                                                                                                                                                                                                                                                                                                                                                                                                                                                       {(((,,) x y (Prelude.True))) -> (((,) x)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            x) ; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                        _ -> (case ((((,,)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          x12)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         y13)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        c13) of
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {(((,,) x y (Prelude.False))) -> (((,) x)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        y) ; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   _ -> (primError "pattern match failure")})}) of
                                                                                                                                                                                                                                                                                                                                                                                                                                                 {(((,) x13 y30)) -> (case (case ((((,,)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        x43)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Prelude.Nothing)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      c44) of
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {(((,,) x y (Prelude.True))) -> (((,) x)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     x) ; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 _ -> (case ((((,,)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   x43)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Prelude.Nothing)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 c44) of
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           {(((,,) x y (Prelude.False))) -> (((,) x)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 y) ; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _ -> (primError "pattern match failure")})}) of
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {(((,) x44 y34)) -> (case (case ((((,,)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 x33)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                y34)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               c34) of
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         {(((,,) x y (Prelude.True))) -> (((,) x)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              x) ; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          _ -> (case ((((,,)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            x33)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           y34)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          c34) of
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {(((,,) x y (Prelude.False))) -> (((,) x)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          y) ; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     _ -> (primError "pattern match failure")})}) of
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   {(((,) x34 y24)) -> (case (case ((((,,)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          x23)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         y24)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        c24) of
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {(((,,) x y (Prelude.True))) -> (((,) x)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       x) ; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   _ -> (case ((((,,)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     x23)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    y24)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   c24) of
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             {(((,,) x y (Prelude.False))) -> (((,) x)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   y) ; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              _ -> (primError "pattern match failure")})}) of
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {(((,) x24 y14)) -> (case (case ((((,,)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   x13)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  y14)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 c14) of
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           {(((,,) x y (Prelude.True))) -> (((,) x)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                x) ; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _ -> (case ((((,,)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              x13)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             y14)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            c14) of
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {(((,,) x y (Prelude.False))) -> (((,) x)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            y) ; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       _ -> (primError "pattern match failure")})}) of
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     {(((,) x14 y40)) -> ((((Main.Maybe4
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 y10)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                y20)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               y30)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              y40) ; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      _ -> (primError "pattern match failure")}) ; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             _ -> (primError "pattern match failure")}) ; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _ -> (primError "pattern match failure")}) ; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           _ -> (primError "pattern match failure")}) ; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                  _ -> (primError "pattern match failure")}) ; 
                                                                                                                                                                                                                                                                                                                                                                                                                         _ -> (primError "pattern match failure")}) ; 
                                                                                                                                                                                                                                                                                                                                                                                                _ -> (primError "pattern match failure")}) ; 
                                                                                                                                                                                                                                                                                                                                                                       _ -> (primError "pattern match failure")}) ; 
                                                                                                                                                                                                                                                                                                                                              _ -> (primError "pattern match failure")}) ; 
                                                                                                                                                                                                                                                                                                                     _ -> (primError "pattern match failure")}) ; 
                                                                                                                                                                                                                                                                                            _ -> (primError "pattern match failure")}) ; 
                                                                                                                                                                                                                                                                   _ -> (primError "pattern match failure")}) ; 
                                                                                                                                                                                                                                          _ -> (primError "pattern match failure")}) ; 
                                                                                                                                                                                                                 _ -> (primError "pattern match failure")}) ; 
                                                                                                                                                                                        _ -> (primError "pattern match failure")}) ; 
                                                                                                                                                               _ -> (primError "pattern match failure")}) ; 
                            _ -> (primError "pattern match failure")})))
Main.devcrossbar :: {- computation -} ReT Main.Inp Main.Out I ()
Main.devcrossbar =
    ((>>= (signal Main.Nix)) (\ i -> (Main.dev i)))
Main.dev :: Main.Inp -> {- computation -} ReT Main.Inp Main.Out I ()
Main.dev =
    (\ $5 -> (case $5 of
                  {((Main.Inp m4 b16)) -> ((>>= (signal
                                                     (Main.Out ((Main.crossbar m4) b16))))
                                               (\ i -> (Main.dev i))) ; 
                   _ -> (case $5 of
                             {((Main.NoInput)) -> ((>>= (signal Main.Nix))
                                                       (\ i -> (Main.dev i))) ; 
                              _ -> (primError "pattern match failure")})}))
Main.start :: {- computation -} ReT Main.Inp Main.Out I ()
Main.start =
    Main.devcrossbar