name:         rewire-core
version:      2.4.0
synopsis:     A Haskell-to-Verilog/VHDL compiler, core library
description:  An experimental compiler for a subset of Haskell to Verilog and VHDL.
homepage:     https://github.com/mu-chaco/ReWire
license:      NONE
license-file: LICENSE
category:     Language
build-type:   Simple
github:       twosixlabs/ReWire.git
maintainer:   Chris Hathhorn <hathhorn@gmail.com>
author:
- Adam Procter
- Chris Hathhorn <hathhorn@gmail.com>
- Ian Graves
- William L. Harrison

ghc-options:
- -Wall
- -fno-warn-name-shadowing
- -funbox-strict-fields
- -O2
- -optc-O3
- -j8 +RTS -A64m -RTS
default-extensions:
- LambdaCase
- TupleSections
- ViewPatterns

extra-source-files:
- README.md

dependencies:
- base ^>= 4.16
- bv ^>= 0.5
- containers ^>= 0.6
- deepseq ^>= 1.4
- directory ^>= 1.3
- exceptions ^>= 0.10
- filepath ^>= 1.4
- ghc ^>= 9.2
- ghc-boot ^>= 9.2
- hashable ^>= 1.4
- haskell-src-exts ^>= 1.23
- lens ^>= 5.1
- machines ^>= 0.7
- megaparsec ^>= 9.2
- mtl ^>= 2.2
- prettyprinter ^>= 1.7
- split ^>= 0.2
- text ^>= 1.2
- text-show ^>= 3.10
- unbound-generics ^>= 0.4
- unordered-containers ^>= 0.2
- yaml ^>= 0.11

library:
  source-dirs: src
