name = "rwv"
version = "0.1.0"
defaultTargets = ["Rwv"]

[[lean_lib]]
name = "Rwv"

[[lean_exe]]
name = "rwv-diff"
root = "Main"

[[lean_exe]]
name = "rwv-parse-check"
root = "ParseCheck"

[[lean_exe]]
name = "rwv-syn-parse-check"
root = "SynParseCheck"

[[lean_exe]]
name = "rwv-synolon-diff"
root = "SynolonDiff"

[[lean_exe]]
name = "rwv-hyle-equiv"
root = "EquivGen"

[[lean_exe]]
name = "rwv-check-equiv"
root = "CheckEquiv"

[[lean_exe]]
name = "rwv-cexp-validate"
root = "CexpValidate"

[[lean_exe]]
name = "rwv-cstep-validate"
root = "CstepValidate"
