name = "rwv"
version = "0.1.0"
defaultTargets = ["Rwv"]

[[lean_lib]]
name = "Rwv"

[[lean_exe]]
name = "rwv-diff"
root = "Main"

[[lean_exe]]
name = "rwv-parse-check"
root = "ParseCheck"

[[lean_exe]]
name = "rwv-eir-parse-check"
root = "EirParseCheck"

[[lean_exe]]
name = "rwv-eidos-diff"
root = "EidosDiff"

[[lean_exe]]
name = "rwv-hyle-equiv"
root = "EquivGen"
