{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE Safe #-}
-- | The Cryptol backend: a direct translation from Core to a self-contained
--   Cryptol module, intended for equivalence checking against hand-written
--   Cryptol specs (e.g. with SAW) and for fast functional simulation. Every
--   Core defn becomes a pure function over bitvectors, and the whole device
--   becomes a stream function @rw_device@ mapping a sequence of per-cycle
--   inputs to a sequence of per-cycle outputs, matching the semantics of the
--   Core interpreter (ReWire.Core.Interp) bit for bit -- including the
--   don't-care convention that a call with a nil alternative takes its branch
--   unconditionally. The rwc-test cosimulation check compares a cryptol
--   evaluation of @rw_device@ against the interpreter's trace.
--
--   Primitive operations mirror the interpreter's semantics: arithmetic is
--   performed at the width @max(result, operands)@ (so carries are preserved,
--   as with Verilog assignment context widths), while complement, shifts, and
--   XNOR are performed at the (left) operand's own width and then resized.
--
--   Externs with no clock and reset are declared as uninterpreted functions
--   in a @parameter@ block (their generic parameters become leading 32-bit
--   arguments); clocked externs and references (rwPrimSetRef/rwPrimGetRef)
--   have no pure-function equivalent and are rejected.
module ReWire.Core.ToCryptol (compileProgram) where

import ReWire.Annotation (Annote)
import ReWire.BitVector (BV, width, bitVec, nat, zeros, (==.))
import ReWire.Config (Config)
import ReWire.Core.Interp (patApply', patMatches', subRange, dispatchWires, resumptionSize, Wiring')
import ReWire.Core.Syntax as C hiding (Name, Size)
import ReWire.Cryptol.Syntax (cryptolName)
import ReWire.Error (failAt, AstError, MonadError)
import ReWire.Pretty (showt)

import qualified ReWire.Cryptol.Syntax as Cry

import Control.Arrow ((&&&))
import Control.Monad (unless)
import Control.Monad.State (StateT, runStateT, modify, gets)
import Data.HashMap.Strict (HashMap)
import Data.HashSet (HashSet)
import Data.List (sortOn)
import Data.Text (Text)

import qualified Data.HashMap.Strict as Map
import qualified Data.HashSet        as Set
import qualified Data.Text           as T

type Size = Cry.Size

-- | Global environment: Core defn name to Cryptol name and signature.
type Env = (HashMap GId Cry.Name, HashMap GId Sig)

data TCS = TCS
      { tcsCtr     :: !Int        -- ^ Per-defn fresh counter for where-bindings.
      , tcsBinds   :: ![Cry.Bind] -- ^ Per-defn where-bindings, in creation order.
      , tcsExterns :: !(HashMap Cry.Name ([Size], Size)) -- ^ Externs encountered so far.
      }

type TCM m = StateT TCS m

compileProgram :: (MonadFail m, MonadError AstError m) => Config -> C.Device -> m Cry.Module
compileProgram _conf p@(C.Device top w loop state0 ds) = do
      (defns, ts) <- runStateT (mapM (transDefn env) allDefns) $ TCS 0 [] mempty
      pure $ Cry.Module modName comments (params $ tcsExterns ts) $ defns <> [deviceDefn env p]
      where modName :: Cry.Name
            modName | T.null top' = "device"
                    | otherwise   = top'
                  where top' = cryptolName top

            allDefns :: [Defn]
            allDefns = loop : state0 : ds

            env :: Env
            env = (buildNames allDefns, Map.fromList $ map (defnName &&& defnSig) allDefns)

            comments :: [Text]
            comments = [ "Generated by rwc from device: " <> top <> "."
                       , "rw_device maps a sequence of per-cycle inputs to per-cycle outputs."
                       ]

            params :: HashMap Cry.Name ([Size], Size) -> [Cry.Param]
            params = map (\ (n, (args, res)) -> Cry.Param n args res) . sortOn fst . Map.toList

-- | Assigns each defn a fresh Cryptol name @rw_<sanitized>@, deduplicating
--   with numeric suffixes (and avoiding the reserved @rw_device@).
buildNames :: [Defn] -> HashMap GId Cry.Name
buildNames = fst . foldl' add (mempty, Set.singleton "rw_device")
      where add :: (HashMap GId Cry.Name, HashSet Cry.Name) -> Defn -> (HashMap GId Cry.Name, HashSet Cry.Name)
            add (m, used) d = (Map.insert (defnName d) n m, Set.insert n used)
                  where n = freshen used $ "rw_" <> cryptolName (defnName d)

            freshen :: HashSet Cry.Name -> Cry.Name -> Cry.Name
            freshen used b | b `Set.member` used = go (2 :: Int)
                           | otherwise           = b
                  where go i | n `Set.member` used = go $ i + 1
                             | otherwise           = n
                              where n = b <> "_" <> showt i

transDefn :: (MonadFail m, MonadError AstError m) => Env -> Defn -> TCM m Cry.Defn
transDefn env (Defn _ g (Sig _ argSizes res) body) = do
      modify $ \ ts -> ts { tcsCtr = 0, tcsBinds = [] }
      e     <- rcast res <$> transExp env lvars body
      binds <- gets tcsBinds
      pure $ Cry.Defn comments (defnNm env g) False args (Cry.TBits res) (fst e) binds
      where args :: [(Cry.Name, Cry.Ty)]
            args = zipWith (\ i sz -> ("arg" <> showt i, Cry.TBits sz)) [0 :: Int ..] argSizes

            lvars :: [(Cry.Exp, Size)]
            lvars = zipWith (\ i sz -> (Cry.Var $ "arg" <> showt i, sz)) [0 :: Int ..] argSizes

            comments :: [Text]
            comments = [g | cryptolName g /= g]

defnNm :: Env -> GId -> Cry.Name
defnNm (names, _) g = Map.findWithDefault ("rw_" <> cryptolName g) g names

fresh :: Monad m => TCM m Cry.Name
fresh = do
      ctr <- gets tcsCtr
      modify $ \ ts -> ts { tcsCtr = ctr + 1 }
      pure $ "s" <> showt ctr

-- | Binds an expression in the where-clause (unless it is already a variable)
--   so pattern slices and match conditions don't duplicate it.
bindScrut :: Monad m => Size -> Cry.Exp -> TCM m Cry.Exp
bindScrut sz = \ case
      e@Cry.Var {} -> pure e
      e            -> do
            n <- fresh
            modify $ \ ts -> ts { tcsBinds = tcsBinds ts <> [Cry.Bind n (Cry.TBits sz) e] }
            pure $ Cry.Var n

transExp :: (MonadFail m, MonadError AstError m) => Env -> [(Cry.Exp, Size)] -> C.Exp -> TCM m (Cry.Exp, Size)
transExp env lvars = \ case
      LVar _ _ (lkupLVal -> Just x) -> pure x
      LVar an _ _                   -> failAt an "ToCryptol: transExp: encountered unknown LVar."
      Lit _ bv                      -> pure (Cry.Lit bv, fromIntegral $ width bv)
      C.Concat _ e1 e2              -> cat' <$> mapM (transExp env lvars) (gather e1 <> gather e2)
      Call an sz tgt e ps els       -> transCall env lvars an sz tgt e ps els
      where lkupLVal :: LId -> Maybe (Cry.Exp, Size)
            lkupLVal = flip lookup (zip [0 :: LId ..] lvars)

transCall :: (MonadFail m, MonadError AstError m)
          => Env -> [(Cry.Exp, Size)] -> Annote -> Size -> Target -> C.Exp -> [Pat] -> C.Exp -> TCM m (Cry.Exp, Size)
transCall env lvars an sz tgt e ps els = do
      (e', we) <- transExp env lvars e
      case e' of
            Cry.Lit bv | patMatchesLit bv ps || C.isNil els -> apply $ patApplyLit bv ps
                       | otherwise                          -> rcast sz <$> transExp env lvars els
            _ -> do
                  scrut <- bindScrut we e'
                  let args  = patApply'   (\ i j     -> [(mkSlice we i j scrut, szR i j)])             ps
                      conds = patMatches' (\ i j bv  -> [Cry.BinOp "==" (mkSlice we i j scrut) $ Cry.Lit bv]) ps
                  r <- apply args
                  if null conds || C.isNil els then pure r
                  else do
                        els' <- rcast sz <$> transExp env lvars els
                        pure (Cry.If (foldr1 (Cry.BinOp "&&") conds) (fst r) (fst els'), sz)
      where apply :: (MonadFail m, MonadError AstError m) => [(Cry.Exp, Size)] -> TCM m (Cry.Exp, Size)
            apply args = case tgt of
                  Global g           -> applyGlobal env an g sz args
                  Prim p             -> applyPrim an p sz args
                  Const bv           -> pure (Cry.Lit $ bitVec (fromIntegral sz) (nat bv), sz)
                  -- An extern with a Haskell model is an ordinary call to the
                  -- model defn; without one it becomes an uninterpreted
                  -- function in the parameter block.
                  Extern _ _ _ (Just g) -> applyGlobal env an g sz args
                  Extern sig ex _ _  -> applyExtern an sig ex sz args
                  SetRef r           -> failAt an $ "ToCryptol: references are not supported by the Cryptol backend (rwPrimSetRef " <> r <> ")."
                  GetRef r           -> failAt an $ "ToCryptol: references are not supported by the Cryptol backend (rwPrimGetRef " <> r <> ")."

            patApplyLit :: BV -> [Pat] -> [(Cry.Exp, Size)]
            patApplyLit bv = patApply' $ \ i j -> [(Cry.Lit $ subRange (i, j) bv, szR i j)]

            patMatchesLit :: BV -> [Pat] -> Bool
            patMatchesLit bv = and . patMatches' (\ i j bv' -> [subRange (i, j) bv ==. bv'])

-- | A pattern slice: 'patApply'' and 'patMatches'' index bits LSB-based
--   ([i, j] inclusive), Cryptol MSB-based.
mkSlice :: Size -> Int -> Int -> Cry.Exp -> Cry.Exp
mkSlice we i j = Cry.slice we (we - 1 - fromIntegral j) (szR i j)

szR :: Int -> Int -> Size
szR i j = fromIntegral $ j - i + 1

applyGlobal :: (MonadFail m, MonadError AstError m) => Env -> Annote -> GId -> Size -> [(Cry.Exp, Size)] -> TCM m (Cry.Exp, Size)
applyGlobal env@(_, sigs) an g sz args = case Map.lookup g sigs of
      Nothing                  -> failAt an $ "ToCryptol: applyGlobal: failed to find definition for " <> g <> "."
      Just (Sig _ argSizes res) -> do
            args' <- alignArgs argSizes args
            pure $ rcast sz (Cry.Call (defnNm env g) args', res)
      where -- | Call-site slices exclude zero-width fields; realign them with
            --   the callee's parameters (any zero-width parameter gets nil).
            alignArgs :: (MonadFail m, MonadError AstError m) => [Size] -> [(Cry.Exp, Size)] -> TCM m [Cry.Exp]
            alignArgs (0 : szs) as              = (Cry.nil :) <$> alignArgs szs as
            alignArgs (w : szs) ((a, wa) : as)  = (fst (rcast w (a, wa)) :) <$> alignArgs szs as
            alignArgs []        []              = pure []
            alignArgs _         _               = failAt an $ "ToCryptol: applyGlobal: argument arity mismatch calling " <> g <> " (rwc bug)."

applyExtern :: (MonadFail m, MonadError AstError m) => Annote -> ExternSig -> Text -> Size -> [(Cry.Exp, Size)] -> TCM m (Cry.Exp, Size)
applyExtern an (ExternSig _ ps clk rst eargs res) ex sz args = do
      unless (T.null clk && T.null rst) $ failAt an
            $ "ToCryptol: clocked extern " <> ex <> " cannot be translated to a pure Cryptol function."
      exts <- gets tcsExterns
      case Map.lookup n exts of
            Just sig' | sig' /= sig -> failAt an $ "ToCryptol: extern " <> ex <> " used with conflicting signatures."
            Just _                  -> pure ()
            Nothing                 -> modify $ \ ts -> ts { tcsExterns = Map.insert n sig exts }
      pure $ rcast sz (Cry.Call n $ genericArgs <> map fst args, resSz)
      where n :: Cry.Name
            n = "ext_" <> cryptolName ex

            sig :: ([Size], Size)
            sig = (map (const 32) ps <> map snd eargs, resSz)

            resSz :: Size
            resSz = sum $ snd <$> res

            genericArgs :: [Cry.Exp]
            genericArgs = map (Cry.Lit . bitVec 32 . toInteger . snd) ps

-- | Primitive operations, with widths chosen to match the Core interpreter
--   (see module header).
applyPrim :: (MonadFail m, MonadError AstError m) => Annote -> Prim -> Size -> [(Cry.Exp, Size)] -> TCM m (Cry.Exp, Size)
applyPrim an p sz args = case (p, args) of
      (Add        , [x, y]) -> pure $ padOp "+"  x y
      (Sub        , [x, y]) -> pure $ padOp "-"  x y
      (Mul        , [x, y]) -> pure $ padOp "*"  x y
      (Div        , [x, y]) -> pure $ padOp "/"  x y
      (Mod        , [x, y]) -> pure $ padOp "%"  x y
      (Pow        , [x, y]) -> pure $ padOp "^^" x y
      (And        , [x, y]) -> pure $ eqOp  "&&" x y
      (Or         , [x, y]) -> pure $ eqOp  "||" x y
      (XOr        , [x, y]) -> pure $ eqOp  "^"  x y
      (XNor       , [x, y]) -> pure $ rcast sz $ notE $ eqOp "^" x y
      (LShift     , [x, y]) -> pure $ shiftOp "<<"  x y
      (RShift     , [x, y]) -> pure $ shiftOp ">>"  x y
      (RShiftArith, [x, y]) -> pure $ shiftOp ">>$" x y
      (Eq         , [x, y]) -> pure $ cmpOp "==" x y
      (Gt         , [x, y]) -> pure $ cmpOp ">"  x y
      (GtEq       , [x, y]) -> pure $ cmpOp ">=" x y
      (Lt         , [x, y]) -> pure $ cmpOp "<"  x y
      (LtEq       , [x, y]) -> pure $ cmpOp "<=" x y
      (LAnd       , [x, y]) -> pure $ bool $ Cry.BinOp "&&" (nonZero x) (nonZero y)
      (LOr        , [x, y]) -> pure $ bool $ Cry.BinOp "||" (nonZero x) (nonZero y)
      (LNot       , [x])    -> pure $ bool $ Cry.BinOp "==" (fst x) zeroE
      (Not        , [x])    -> pure $ rcast sz $ notE x
      (RAnd       , [x])    -> pure $ bool $ Cry.BinOp "==" (fst x) $ Cry.UnOp "~" zeroE
      (RNAnd      , [x])    -> pure $ bool $ Cry.BinOp "!=" (fst x) $ Cry.UnOp "~" zeroE
      (ROr        , [x])    -> pure $ bool $ Cry.BinOp "!=" (fst x) zeroE
      (RNor       , [x])    -> pure $ bool $ Cry.BinOp "==" (fst x) zeroE
      (RXOr       , [x])    -> pure $ bool $ Cry.Call "rw'parity" [fst x]
      (RXNor      , [x])    -> pure $ bool $ Cry.UnOp "~" $ Cry.Call "rw'parity" [fst x]
      (MSBit      , [(x, w1)])
            | w1 > 0          -> pure $ bool $ Cry.Index x 0
            | otherwise       -> pure $ rcast sz (Cry.Lit $ zeros 1, 1)
      (Resize     , [x])    -> pure $ rcast sz x
      (Id         , _)      -> pure $ rcast sz $ cat' args
      (Reverse    , _)      -> pure $ rcast sz $ cat' $ reverse args
      (Replicate n, [(x, w1)]) -> pure $ rcast sz (Cry.TCall "rw'repl" n [x], fromIntegral n * w1)
      _                     -> failAt an $ "ToCryptol: applyPrim: unsupported primitive or arity: " <> showt p <> "."
      where -- | Arithmetic at width max(sz, w1, w2): equivalent to the
            --   interpreter's compute-unbounded-then-truncate.
            padOp :: Cry.Name -> (Cry.Exp, Size) -> (Cry.Exp, Size) -> (Cry.Exp, Size)
            padOp op x y = rcast sz (Cry.BinOp op (ext ww x) (ext ww y), ww)
                  where ww = maximum [sz, snd x, snd y]

            -- | Bitwise ops at width max(w1, w2), then resized.
            eqOp :: Cry.Name -> (Cry.Exp, Size) -> (Cry.Exp, Size) -> (Cry.Exp, Size)
            eqOp op x y = rcast sz (Cry.BinOp op (ext we x) (ext we y), we)
                  where we = max (snd x) (snd y)

            -- | Shifts at the left operand's own width (the interpreter
            --   discards bits shifted beyond it), then resized; the shift
            --   amount keeps its own width.
            shiftOp :: Cry.Name -> (Cry.Exp, Size) -> (Cry.Exp, Size) -> (Cry.Exp, Size)
            shiftOp op (x, w1) (y, _)
                  | w1 > 0    = rcast sz (Cry.BinOp op x y, w1)
                  | otherwise = rcast sz (Cry.nil, 0)

            -- | Comparisons on operands zero-extended to a common width.
            cmpOp :: Cry.Name -> (Cry.Exp, Size) -> (Cry.Exp, Size) -> (Cry.Exp, Size)
            cmpOp op x y = bool $ Cry.BinOp op (ext we x) (ext we y)
                  where we = max (snd x) (snd y)

            notE :: (Cry.Exp, Size) -> (Cry.Exp, Size)
            notE (x, w1) = (Cry.UnOp "~" x, w1)

            nonZero :: (Cry.Exp, Size) -> Cry.Exp
            nonZero (x, _) = Cry.BinOp "!=" x zeroE

            zeroE :: Cry.Exp
            zeroE = Cry.Var "zero"

            -- | A Bit-valued expression as a [1], resized to the result width.
            bool :: Cry.Exp -> (Cry.Exp, Size)
            bool e = rcast sz (Cry.Sing e, 1)

            ext :: Size -> (Cry.Exp, Size) -> Cry.Exp
            ext we (x, wx) | we == wx  = x
                           | otherwise = Cry.resize we x

cat' :: [(Cry.Exp, Size)] -> (Cry.Exp, Size)
cat' es = (Cry.cat $ map fst es', sum $ map snd es')
      where es' = filter ((> 0) . snd) es

rcast :: Size -> (Cry.Exp, Size) -> (Cry.Exp, Size)
rcast sz (e, w) | w == sz   = (e, w)
                | otherwise = (Cry.resize sz e, sz)

-- | The Mealy-machine wrapper: for a clocked device, the canonical Cryptol
--   stream idiom (a self-referential state stream seeded by the initial
--   state); for a purely combinational device, just a map over the inputs.
--   The output is computed from the current state and inputs in the same
--   cycle, matching the Core interpreter (and the testbenches' sampling).
deviceDefn :: Env -> C.Device -> Cry.Defn
deviceDefn env (C.Device top w loop state0 _)
      | dSz > 0 = Cry.Defn comments "rw_device" True [("ins", insTy)] outsTy (Cry.Var "outs")
            [ Cry.Bind "rs" (Cry.TSeq Cry.LenVar $ Cry.TBits resSz)
                  $ Cry.Comp (Cry.Call loopN $ [Cry.Var "st" | dSz > 0] <> [Cry.Var "i" | iw > 0])
                  $ ("st", Cry.Var "sts") : [inArm]
            , Cry.Bind "sts" (Cry.TSeq Cry.LenSucc $ Cry.TBits dSz)
                  $ Cry.BinOp "#" (Cry.SeqLit [nxt $ Cry.Var st0N])
                  $ Cry.Comp (nxt $ Cry.Var "r") [("r", Cry.Var "rs")]
            , Cry.Bind "outs" outsTy
                  $ Cry.Comp (out $ Cry.Var "r") [("r", Cry.Var "rs")]
            ]
      | otherwise = Cry.Defn comments "rw_device" True [("ins", insTy)] outsTy
            (Cry.Comp (out $ Cry.Call loopN [Cry.Var "i" | iw > 0]) [inArm]) []
      where w' :: Wiring'
            w' = (w, defnSig loop, defnSig state0)

            iw, ow, dSz, resSz, padSz :: Size
            iw    = sum $ snd <$> inputWires w
            ow    = sum $ snd <$> outputWires w
            dSz   = sum $ snd <$> dispatchWires w'
            resSz = resumptionSize w'
            padSz = resSz - ow - dSz

            insTy, outsTy :: Cry.Ty
            insTy  = Cry.TSeq Cry.LenVar $ Cry.TBits iw
            outsTy = Cry.TSeq Cry.LenVar $ Cry.TBits ow

            loopN, st0N :: Cry.Name
            loopN = defnNm env $ defnName loop
            st0N  = defnNm env $ defnName state0

            inArm :: (Cry.Name, Cry.Exp)
            inArm | iw > 0    = ("i", Cry.Var "ins")
                  | otherwise = ("_", Cry.Var "ins")

            -- | Loop results have the layout (MSB-first): padding, outputs,
            --   next dispatch state.
            out, nxt :: Cry.Exp -> Cry.Exp
            out = Cry.slice resSz padSz ow
            nxt = Cry.slice resSz (padSz + ow) dSz

            comments :: [Text]
            comments = [ "Device: " <> top
                       , "Inputs, MSB-first: "  <> wires (inputWires w)
                       , "Outputs, MSB-first: " <> wires (outputWires w)
                       ]

            wires :: [(Text, Size)] -> Text
            wires = \ case
                  [] -> "(none)"
                  ws -> T.intercalate ", " $ map (\ (n, s) -> n <> " : [" <> showt s <> "]") ws
