-- VHDL equivalents of the extern modules in ../verilog/filterprims.sv, for
-- the rwc-test cosimulation check. Port names match the component
-- declarations generated by the VHDL backend (p<i> for unnamed extern ports).
library ieee;
use ieee.std_logic_1164.all;

entity test1 is
  port (p0 : in std_logic_vector (31 downto 0);
        p1 : in std_logic_vector (31 downto 0);
        p2 : out std_logic_vector (0 downto 0));
end entity;
architecture rtl of test1 is
begin
  p2(0) <= p0(0) and p1(0);
end architecture;

library ieee;
use ieee.std_logic_1164.all;

entity test2 is
  port (p0 : in std_logic_vector (31 downto 0);
        p1 : in std_logic_vector (31 downto 0);
        p2 : out std_logic_vector (0 downto 0));
end entity;
architecture rtl of test2 is
begin
  p2(0) <= p0(0) and p1(0);
end architecture;

library ieee;
use ieee.std_logic_1164.all;

entity test3 is
  port (p0 : in std_logic_vector (31 downto 0);
        p1 : in std_logic_vector (31 downto 0);
        p2 : out std_logic_vector (0 downto 0));
end entity;
architecture rtl of test3 is
begin
  p2(0) <= p0(0) and p1(0);
end architecture;

library ieee;
use ieee.std_logic_1164.all;

entity test4 is
  port (p0 : in std_logic_vector (31 downto 0);
        p1 : in std_logic_vector (31 downto 0);
        p2 : out std_logic_vector (0 downto 0));
end entity;
architecture rtl of test4 is
begin
  p2(0) <= p0(0) and p1(0);
end architecture;
