-- VHDL equivalents of the extern modules in ../verilog/w32ops.sv, for the
-- rwc-test cosimulation check. Port names match the component declarations
-- generated by the VHDL backend (p<i> for unnamed extern ports).
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity \plusW32\ is
  port (p0 : in std_logic_vector (31 downto 0);
        p1 : in std_logic_vector (31 downto 0);
        p2 : out std_logic_vector (31 downto 0));
end entity;
architecture rtl of \plusW32\ is
begin
  p2 <= std_logic_vector(unsigned(p0) + unsigned(p1));
end architecture;

library ieee;
use ieee.std_logic_1164.all;

entity \andW32\ is
  port (p0 : in std_logic_vector (31 downto 0);
        p1 : in std_logic_vector (31 downto 0);
        p2 : out std_logic_vector (31 downto 0));
end entity;
architecture rtl of \andW32\ is
begin
  p2 <= p0 and p1;
end architecture;

library ieee;
use ieee.std_logic_1164.all;

entity \xorW32\ is
  port (p0 : in std_logic_vector (31 downto 0);
        p1 : in std_logic_vector (31 downto 0);
        p2 : out std_logic_vector (31 downto 0));
end entity;
architecture rtl of \xorW32\ is
begin
  p2 <= p0 xor p1;
end architecture;

library ieee;
use ieee.std_logic_1164.all;

entity \notW32\ is
  port (p0 : in std_logic_vector (31 downto 0);
        p1 : out std_logic_vector (31 downto 0));
end entity;
architecture rtl of \notW32\ is
begin
  p1 <= not p0;
end architecture;
